Combobox updated
GovWifi/govwifi-admin pull request #2141
Opened 2024-10-15 14:04 UTC by mel-am

### What

On the 'Organisations allow list' page, there is a search combobox that lacks an accessible name, due to the visually associated label 'Search for existing organisations on GovWifi before adding them' not being programmatically associated with the input. Lacking this programmatic association, the accessible name fallbacks to using the placeholder attribute on the input, but this placeholder is empty. Therefore, leaving the input without an accessible name overall. This affects screen reader users, as the input is not labelled and, therefore, its purpose is not programmatically determinable (particularly when browsing out of context), and it also DAC | Accessibility Report 45 affects voice activation users, as there is no programmatic association between the visible label and the input for the user to select the input via its visible label ('click search for existing organisations…').
### Why

The label and combobox are not programmatically associated with each other.

Link to JIRA card (if applicable):
[GW-1916](https://technologyprogramme.atlassian.net/browse/GW-1916)

2024-10-17 08:40 UTC, koetsier requested changes

2024-10-17 08:40 UTC, koetsier commented on app/views/super_admin/allowlists/organisation_names/index.html.erb
> +    <%# <%= label_tag "organisations_register","search_orgs_label", "Search for existing organisations on GovWifi before adding them", class: "govuk-label" %>
Could you remove the commented-out lines?

2024-10-17 08:40 UTC, koetsier commented on app/views/super_admin/allowlists/organisation_names/index.html.erb
> +    <%= select_tag "organisations_register", options_for_select(@fetched_organisations_from_register, ""), class: "govuk-select", id: "organisations_register" %>
do we not need the `<< ""` bit in `options_for_select(@fetched_organisations_from_register << "", "")` anymore?

2024-10-22 15:24 UTC, leonaAtkins commented
So when I tested this with JAWS, my screen reader, I navigated to the Allow org allow list page, tabbed to the button which read it out, then on to the combo box, which read out 'Search for existing organisations on GovWifi before adding them' typed in 'UK', eventually it told me the number of results and I could scroll up and down and JAWS would read out the results, no whether it's running it locally that's the issue of the slowness or something up with the JavaScript search script, but in terms of UI, it does now read out the results.

2024-10-22 15:27 UTC, leonaAtkins approved these changes

2024-10-28 17:09 UTC, leonaAtkins approved these changes
it now reads fine, and I able able to search, it's still really slow to search, but it could be a local thing to my machine, anyone else see this? (separate issue).

2025-01-27 15:13 UTC, koetsier approved these changes
lgtm

2025-01-28 12:13 UTC, merged